-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-01-11 17:26:36 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE school_attendance 
    ( 
     id_attendance              NUMBER  NOT NULL , 
     "date"                     DATE  NOT NULL , 
     status                     VARCHAR2 (20)  NOT NULL , 
     school_students_id_student NUMBER  NOT NULL , 
     school_subjects_id_subject NUMBER  NOT NULL , 
     school_teachers_id_teacher NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_attendance 
    ADD CONSTRAINT school_attendance_PK PRIMARY KEY ( id_attendance ) ;

CREATE TABLE school_classes 
    ( 
     id_class                   NUMBER  NOT NULL , 
     class_name                 VARCHAR2 (20)  NOT NULL , 
     class_profile              VARCHAR2 (50)  NOT NULL , 
     school_teachers_id_teacher NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_classes 
    ADD CONSTRAINT school_classes_PK PRIMARY KEY ( id_class ) ;

CREATE TABLE school_grades 
    ( 
     id_grade                   NUMBER  NOT NULL , 
     grade                      NUMBER  NOT NULL , 
     grade_date                 DATE  NOT NULL , 
     school_teachers_id_teacher NUMBER  NOT NULL , 
     school_students_id_student NUMBER  NOT NULL , 
     school_subjects_id_subject NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_grades 
    ADD CONSTRAINT school_grades_PK PRIMARY KEY ( id_grade ) ;

CREATE TABLE school_guardians 
    ( 
     id_guardian NUMBER  NOT NULL , 
     first_name  VARCHAR2 (50)  NOT NULL , 
     last_name   VARCHAR2 (50)  NOT NULL , 
     phone       VARCHAR2 (20)  NOT NULL , 
     email       VARCHAR2 (100)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_guardians 
    ADD CONSTRAINT school_guardians_PK PRIMARY KEY ( id_guardian ) ;

CREATE TABLE school_note 
    ( 
     id_note                    NUMBER  NOT NULL , 
     "date"                     DATE  NOT NULL , 
     note_text                  VARCHAR2 (4000)  NOT NULL , 
     school_teachers_id_teacher NUMBER  NOT NULL , 
     school_students_id_student NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_note 
    ADD CONSTRAINT school_note_PK PRIMARY KEY ( id_note ) ;

CREATE TABLE school_student_guardians 
    ( 
     id_student_guardian          NUMBER  NOT NULL , 
     relationship                 VARCHAR2 (100) , 
     school_guardians_id_guardian NUMBER  NOT NULL , 
     school_students_id_student   NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_student_guardians 
    ADD CONSTRAINT school_student_guardians_PKv1 PRIMARY KEY ( id_student_guardian ) ;

CREATE TABLE school_students 
    ( 
     id_student              NUMBER  NOT NULL , 
     first_name              VARCHAR2 (50)  NOT NULL , 
     last_name               VARCHAR2 (50)  NOT NULL , 
     birth_date              DATE  NOT NULL , 
     school_classes_id_class NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_students 
    ADD CONSTRAINT school_students_PK PRIMARY KEY ( id_student ) ;

CREATE TABLE school_subjects 
    ( 
     id_subject   NUMBER  NOT NULL , 
     subject_name VARCHAR2 (50)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_subjects 
    ADD CONSTRAINT school_subjects_PK PRIMARY KEY ( id_subject ) ;

CREATE TABLE school_teacher_subjects 
    ( 
     id_teacher_subject         NUMBER  NOT NULL , 
     school_teachers_id_teacher NUMBER  NOT NULL , 
     school_subjects_id_subject NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_teacher_subjects 
    ADD CONSTRAINT school_teacher_subjects_PK PRIMARY KEY ( id_teacher_subject ) ;

--DROP TABLE school_teachers CASCADE CONSTRAINTS;

CREATE TABLE school_teachers (
    id_teacher NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    birth_date DATE,           
    email VARCHAR2(100),
    phone VARCHAR2(20)
);

--ALTER TABLE school_teachers 
 --   ADD CONSTRAINT school_teachers_PK PRIMARY KEY ( id_teacher ) ;

CREATE TABLE school_users 
    ( 
     id_user      NUMBER  NOT NULL , 
     login        VARCHAR2 (50)  NOT NULL , 
     password     VARCHAR2 (100)  NOT NULL , 
     role         VARCHAR2 (20)  NOT NULL , 
     fk_person_id NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE school_users 
    ADD CONSTRAINT school_users_PK PRIMARY KEY ( id_user ) ;

ALTER TABLE school_students 
    ADD CONSTRAINT school_classes_FK FOREIGN KEY 
    ( 
     school_classes_id_class
    ) 
    REFERENCES school_classes 
    ( 
     id_class
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_student_guardians 
    ADD CONSTRAINT school_guardians_FK FOREIGN KEY 
    ( 
     school_guardians_id_guardian
    ) 
    REFERENCES school_guardians 
    ( 
     id_guardian
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_attendance 
    ADD CONSTRAINT school_students_FK FOREIGN KEY 
    ( 
     school_students_id_student
    ) 
    REFERENCES school_students 
    ( 
     id_student
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_grades 
    ADD CONSTRAINT school_students_FKv1 FOREIGN KEY 
    ( 
     school_students_id_student
    ) 
    REFERENCES school_students 
    ( 
     id_student
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_note 
    ADD CONSTRAINT school_students_FKv3 FOREIGN KEY 
    ( 
     school_students_id_student
    ) 
    REFERENCES school_students 
    ( 
     id_student
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_student_guardians 
    ADD CONSTRAINT school_students_FKv4 FOREIGN KEY 
    ( 
     school_students_id_student
    ) 
    REFERENCES school_students 
    ( 
     id_student
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_attendance 
    ADD CONSTRAINT school_subjects_FK FOREIGN KEY 
    ( 
     school_subjects_id_subject
    ) 
    REFERENCES school_subjects 
    ( 
     id_subject
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_grades 
    ADD CONSTRAINT school_subjects_FKv1 FOREIGN KEY 
    ( 
     school_subjects_id_subject
    ) 
    REFERENCES school_subjects 
    ( 
     id_subject
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_attendance 
    ADD CONSTRAINT school_teachers_FK FOREIGN KEY 
    ( 
     school_teachers_id_teacher
    ) 
    REFERENCES school_teachers 
    ( 
     id_teacher
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_grades 
    ADD CONSTRAINT school_teachers_FKv1 FOREIGN KEY 
    ( 
     school_teachers_id_teacher
    ) 
    REFERENCES school_teachers 
    ( 
     id_teacher
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_classes 
    ADD CONSTRAINT school_teachers_FKv2 FOREIGN KEY 
    ( 
     school_teachers_id_teacher
    ) 
    REFERENCES school_teachers 
    ( 
     id_teacher
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_note 
    ADD CONSTRAINT school_teachers_FKv3 FOREIGN KEY 
    ( 
     school_teachers_id_teacher
    ) 
    REFERENCES school_teachers 
    ( 
     id_teacher
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_teacher_subjects 
    ADD CONSTRAINT subjects_school_subjects_FK FOREIGN KEY 
    ( 
     school_subjects_id_subject
    ) 
    REFERENCES school_subjects 
    ( 
     id_subject
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE school_teacher_subjects 
    ADD CONSTRAINT subjects_school_teachers_FK FOREIGN KEY 
    ( 
     school_teachers_id_teacher
    ) 
    REFERENCES school_teachers 
    ( 
     id_teacher
    ) 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
